# Generated by Django 4.2.13 on 2024-07-31 20:38

from django.db import migrations, models
import django.db.models.deletion
import uploadfileapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('cvFile', models.FileField(blank=True, null=True, upload_to='employee_files/cv/')),
                ('photoFile', models.FileField(blank=True, null=True, upload_to='employee_files/photo/')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateFile', models.FileField(blank=True, null=True, upload_to=uploadfileapp.models.certificate_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadfileapp.employee')),
            ],
        ),
    ]
